version: '3'

services:
  db:
    image: postgres

    container_name: todo-postgres

    restart: always

    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: todo-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass456
